version: "2"
checks:
  file-lines:
    config:
      threshold: 270
  method-lines:
    config:
      threshold: 27  # 2 more to ignore the surrounding { }
exclude_patterns:
  - "libNOM.test/"
  - "libNOM.io/Interfaces/"  # it takes as much methods as it takes. making an interface partial would not add much to the overall maintainability
  - "libNOM.io/Global/Constants.cs"  # exclude as it may not avoidable to have similar definitions
  - "libNOM.io/Platform*_Trace.cs"  # somewhat dublicates existing code as it will be created after the general platform initialization
